### ISSUE TITLE
Combination with MMM-iFrame-Ping module blocks display of TomTom Map.

### ISSUE THREAD

**Issue by Egorarchitec** [Travelbacon/MMM-TomTomTrafficIncidents#5]
Hi, I am trying to use your plugin, and it worked great till the moment I added an independent iframe module to show a flightradar map on a screen. When I add iframe (doesn't matter what it is displaying, what size, or where it is located) TomTom just won't load. When I delete the iframe module it starts to work again. Where can be a problem? I want to use your module, it is good for my purpose.
with iframe
![image](https://user-images.githubusercontent.com/66465822/104942071-3bf79a00-59b4-11eb-9672-ecc84a890d7e.png)
without iframe
![image](https://user-images.githubusercontent.com/66465822/104942299-90027e80-59b4-11eb-8eb0-3941f5d1e146.png)

don't mind the overlapping modules, on my vertical oriented display it is ok :)

**Comment by Travelbacon** [comment]
Okay. That is strange. What does the debug output says when you activate the flight radar?

**Comment by Egorarchitec** [comment]
[MagicMirror-error.log](https://github.com/Travelbacon/MMM-TomTomTrafficIncidents/files/5838497/MagicMirror-error.log)
[MagicMirror-out.log](https://github.com/Travelbacon/MMM-TomTomTrafficIncidents/files/5838498/MagicMirror-out.log)

There are MM logs from the time I posted my screenshots. I do not see anything about iframe TomTom modules there that would be useful...  Or there are other logs I need to look at? And one detail. It is not specific to FlightRadar24. I think it is a behavior of TomTom. Because any module with iframe functionality breaks TomTom module. doesn't matter what kind of web page is displayed in said iframe, presence of it itself unrenders TomTom.

For my usage I just created two separate layouts that cronjob switches in set time, because tomtom module is useful only in the morning. So it is not an actual issue for me anymore. But might be an issue for someone else

**Comment by Travelbacon** [comment]
Thanks. The problem starts in the module remote control, not in the flight tracker.
It could be anything from a memory leak or other something of violation. I have to deep in to that part.

Does your mirror work if you only configure this module and the flight module?

**Comment by Egorarchitec** [comment]
I deleted all modules but iFrame-Ping and TomTomTrafficIncidents and still I see only iframe content...

**Comment by Travelbacon** [comment]
I have to try to reproduce it here.
Can you give me URL of the iFrame module please?
You use a Pi as server?

**Comment by Egorarchitec** [comment]
I use Pi 4B 8GB as a server. 
module I use is https://github.com/AgP42/MMM-iFrame-Ping but there is no difference in what iframe module you would use. I tried iframe, iframe-ping, yframe. Every combination behave the same way.

**Comment by Travelbacon** [comment]
I've done some thorough testing. The problem is not caused in this module. Somewhere in the iframe-ping and helper there is some sort of memory leak that is causing the malfunction in the display in the TomTom API. I took the stable v5 and my beta of v6 module from this repo.

What I can see is that MMM-iFrame-Ping has some issues by itself. You can only call one module in the configuration. When you define more MMM-iFrame-Ping in the config, only the last one will run and the other ones will only display the PING result.

The owner of this module should fix this issue first. In mean time I keep this bug report open. Perhaps it still on this side of the module proven with other modules.

**Comment by TitouBilou** [comment]
Hi Guys,
I did not solve the problem but I am bringing a new piece of information that may help you (Travelbacon) to solve it.
I have exactly the same problem as described by Egorarchitec but my other module is different : It's MMM-RAIN-RADAR.
MMM-TomTomTrafficIncidents was working fine until I installed MMM-RAIN-RADAR.
If I get rid off MMM-RAIN-RADAR, MMM-TomTomTrafficIncidents starts to work fine again (I have another 12-15 modules that are working fine on a RPi 4B 4GB).
I hope this helps... I've reached the limits of my competencies...

Titou.

**Comment by Travelbacon** [comment]
Thanks. I have to look deeper in it. I think that there is an overlap in a global variable. Because I can't change the module MMM-RAIN-RADAR I have to look in mine module. I pick this up as well that the zoom-level visibility has been changed by TomTom.
